services:
  client:
    build:
      target: prod
    volumes:
      - /app/node_modules
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=http://localhost:3001
      - NGINX_SERVER_NAME=gojoe.dev
    secrets:
      - cloudflare_cert
      - cloudflare_key

  server:
    build:
      target: prod
    volumes:
      - /app/tmp
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/argodb

  mongo:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_prod_data:/data/db

volumes:
  mongodb_prod_data:

secrets:
  cloudflare_cert:
    file: ./cloudflare.crt
  cloudflare_key:
    file: ./cloudflare.key
