services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/argodb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
